#!/bin/bash

#: Title:           readlines
#: Date:            Fri Jun 21 06:26:55 DST 2019
#: Author:          WessCoby
#: Version:         1.0.0
#: Description:     Script to read lines from a csv file

### Reading and outputing lines at specified interval
interval=0.000000000000000000001

count=0
while read -r line;
do
    [ $count -ge 1 ] && echo $line;     ### Ignore the first line [header]
    let count++;
    sleep $interval;
done < $1                               ### CSV file argument