#!/bin/bash

#: Title:           readlines
#: Date:            Fri Jun 21 06:26:55 DST 2019
#: Author:          WessCoby
#: Version:         1.0.0
#: Description:     Script to read lines from a csv file

count=0
while read -r line;
do
    [ $count -ge 1 ] && echo $line;
    let count++;
    sleep 0.1;
done < $1